import React from 'react';
import SitemapSection from '@/components/sections/SitemapSection';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Site Map',
  description: 'A complete overview of all pages on our website.',
  robots: 'noindex, nofollow',
};

export default function SitemapStaticPage() {
  const defaultSitemapData = {
    title: 'Site Map',
    description: 'A complete overview of all pages on our website.',
    mainPages: [
      { label: 'Home', url: '/' },
      { label: 'About Us', url: '/about-us/' },
      { label: 'How It Works', url: '/how-it-works/' },
      { label: 'Contact Us', url: '/contact-us/' },
      { label: 'Schedule Appointment', url: '/schedule-appointment/' },
      { label: 'Blog', url: '/blog/' },
      { label: 'Privacy Policy', url: '/privacy-policy/' },
      { label: 'Terms & Conditions', url: '/terms-conditions/' },
    ],
    caseStudies: [
      { label: 'All Case Studies', url: '/case-study/' },
      { label: 'HVAC', url: '/case-study/hvac/' },
      { label: 'Zenison Spa Therapy', url: '/case-study/zenison-spa-therapy/' },
      { label: 'Investigation Hotline', url: '/case-study/investigation-hotline/' },
      { label: 'Locks and Door', url: '/case-study/locks-and-door/' },
      { label: 'Locksmith', url: '/case-study/locksmith/' },
      { label: 'Home Decor', url: '/case-study/home-decor/' },
      { label: 'Blogging Website', url: '/case-study/blogging-website/' },
      { label: 'Automotive', url: '/case-study/automotive/' },
      { label: 'Finance', url: '/case-study/finance/' },
      { label: 'Auto Parts', url: '/case-study/auto-parts/' },
      { label: 'Universal Pest Control', url: '/case-study/universal-pest-control/' },
      { label: 'Auto Protect', url: '/case-study/auto-protect/' },
      { label: 'iRetex Premier', url: '/case-study/iretex-premier/' },
      { label: 'Water WorkzTX', url: '/case-study/water-workztx/' },
      { label: 'She Lives Beauty', url: '/case-study/she-lives-beauty/' },
      { label: 'GK Blinds', url: '/case-study/gkblinds/' },
      { label: '911 Garage Door Pros', url: '/case-study/911-garage-door-pros/' },
      { label: 'Just Voda', url: '/case-study/just-voda/' },
      { label: 'Rehvive', url: '/case-study/rehvive/' },
      { label: 'Lifecore Flooring', url: '/case-study/lifecore-flooring/' },
      { label: 'Dollar General', url: '/case-study/dollar-general/' },
    ],
    reviewProducts: [
      { label: 'Buy Reviews Online', url: '/services/buy-reviews-online/' },
      { label: 'Ambition Box Reviews', url: '/products/ambition-box-reviews/' },
      { label: 'Apartment Reviews', url: '/products/buy-apartment-reviews/' },
      { label: 'AutoTrader Reviews', url: '/products/autotrader-reviews/' },
      { label: 'Avvo Reviews', url: '/products/avvo-reviews/' },
      { label: 'Bark Reviews', url: '/products/bark-reviews/' },
      { label: 'BBB Reviews', url: '/products/buy-bbb-reviews/' },
      { label: 'Birdeye Reviews', url: '/products/birdeye-reviews/' },
      { label: 'Booking Reviews', url: '/products/booking-com-reviews/' },
      { label: 'BookMyShow Reviews', url: '/products/bookmyshow-reviews/' },
      { label: 'BuildZoom Reviews', url: '/products/buildzoom-reviews/' },
      { label: 'CarGurus Reviews', url: '/products/cargurus-reviews/' },
      { label: 'ChamberofCommerce Reviews', url: '/products/chamberofcommerce/' },
      { label: 'Chrome Extension Reviews', url: '/products/buy-chrome-extension-reviews/' },
      { label: 'Consumeraffairs.com Reviews', url: '/products/consumeraffairs-com-reviews/' },
      { label: 'CustomerLobby Reviews', url: '/products/customerlobby-reviews/' },
      { label: 'Dealerrater Reviews', url: '/products/dealerrater-reviews/' },
      { label: 'Designrush Reviews', url: '/products/designrush-reviews/' },
      { label: 'Energysage Reviews', url: '/products/energysage-reviews/' },
      { label: 'Expedia Reviews', url: '/products/expedia-reviews/' },
      { label: 'Facebook Reviews', url: '/products/facebook-reviews/' },
      { label: 'Findlaw Reviews', url: '/products/findlaw-reviews/' },
      { label: 'FoodDrop Reviews', url: '/products/fooddrop-reviews/' },
      { label: 'Free Google Reviews', url: '/grb/product/get-free-google-reviews/' },
      { label: 'Glassdoor Reviews', url: '/products/buy-glassdoor-reviews/' },
      { label: 'Google GPS Reviews', url: '/products/google-gps-reviews/' },
      { label: 'Google Local Guide Reviews', url: '/products/buy-google-local-guide-reviews/' },
      { label: 'Google LSA Reviews', url: '/products/google-lsa-reviews/' },
      { label: 'Google Playstore Reviews', url: '/products/buy-google-play-store-reviews/' },
      { label: 'Google Reviews', url: '/products/buy-google-review/' },
      { label: 'Healthgrades Reviews', url: '/products/healthgrades-reviews/' },
      { label: 'HelloPeter.com Reviews', url: '/products/hellopeter-reviews/' },
      { label: 'Home Advisor Reviews', url: '/products/buy-home-advisor-reviews/' },
      { label: 'Home Star Reviews', url: '/products/homestars-reviews/' },
      { label: 'HomeToGo Reviews', url: '/products/hometogo-reviews/' },
      { label: 'Homelight Reviews', url: '/products/buy-homelight-reviews/' },
      { label: 'Hotels Reviews', url: '/products/hotels-com-reviews/' },
      { label: 'Houzz Reviews', url: '/products/buy-houzz-reviews/' },
      { label: 'IMDb Reviews', url: '/products/imdb-reviews/' },
      { label: 'Indeed Reviews', url: '/products/indeed-reviews/' },
      { label: 'JobStreet Reviews', url: '/products/jobstreet-reviews/' },
      { label: 'Magikpet Reviews', url: '/products/magikpet-reviews/' },
      { label: 'Makeupalley Reviews', url: '/products/makeupalley-reviews/' },
      { label: 'Mortgage Matchup Reviews', url: '/products/mortgage-matchupreviews/' },
      { label: 'Networx Reviews', url: '/products/networx-reviews/' },
      { label: 'Niche.com Reviews', url: '/products/niche-reviews/' },
      { label: 'Product Reviews', url: '/products/product-reviews/' },
      { label: 'QuickBooks Review', url: '/products/quickbooks-review/' },
      { label: 'RateMds Reviews', url: '/products/ratemds-reviews/' },
      { label: 'RealEstateAgents Reviews', url: '/products/realestateagents-reviews/' },
      { label: 'RealSelf Reviews', url: '/products/realself-reviews/' },
      { label: 'Realtor Reviews', url: '/products/buy-realtor-reviews/' },
      { label: 'Rehab.com Reviews', url: '/products/rehab-reviews/' },
      { label: 'ReportTotal Reviews', url: '/products/reporttotal-reviews/' },
      { label: 'Review Centre Reviews', url: '/products/review-centre-reviews/' },
      { label: 'Reviews.io Reviews', url: '/products/reviews-io-reviews/' },
      { label: 'REW Reviews', url: '/products/rew-reviews/' },
      { label: 'SaaSHub Reviews', url: '/products/saashub-reviews/' },
      { label: 'Scamvoid Reviews', url: '/products/scamvoid-reviews/' },
      { label: 'Seek.com Reviews', url: '/products/seek-com/' },
      { label: 'Sitejabber Reviews', url: '/products/sitejabber-reviews/' },
      { label: 'Solar Choice', url: '/products/solar-choice/' },
      { label: 'Solar Reviews', url: '/products/solarreviews/' },
      { label: 'Sortlist Reviews', url: '/products/sortlist-reviews/' },
      { label: 'Source Forge Reviews', url: '/products/source-forge-reviews/' },
      { label: 'Spotify', url: '/products/spotify/' },
      { label: 'Thumbtack Reviews', url: '/products/thumbtack-reviews/' },
      { label: 'TopSEOs Reviews', url: '/products/topseos-reviews/' },
      { label: 'Transport Reviews', url: '/products/transport-reviews/' },
      { label: 'TrustPilot Reviews', url: '/products/buy-trustpilot-reviews/' },
      { label: 'Trustpilot Verified Reviews', url: '/products/trustpilot-verified-reviews/' },
      { label: 'Trustedpros Reviews', url: '/products/trustedpros/' },
      { label: 'UpCity Reviews', url: '/products/upcity-reviews/' },
      { label: 'Vitals Reviews', url: '/products/vitals-com-reviews/' },
      { label: 'Web Retailer Reviews', url: '/products/web-retailer-reviews/' },
      { label: 'WebMD Reviews', url: '/products/webmd-reviews/' },
      { label: 'WeddingWire Reviews', url: '/products/weddingwire-reviews/' },
      { label: 'WYL.co Reviews', url: '/products/wyl-page-reviews/' },
      { label: 'YellowPages Reviews', url: '/products/buy-yellowpages-reviews/' },
      { label: 'Yelp Reviews', url: '/products/buy-5-star-positive-yelp-reviews/' },
      { label: 'Zillow Reviews', url: '/products/buy-zillow-reviews/' },
    ],
  };

  return <SitemapSection id="static-sitemap" data={defaultSitemapData} settings={{} as any} />;
}
