import React from 'react';
import SitemapSection from '@/components/sections/SitemapSection';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Site Map',
  description: 'A complete overview of all pages on our website.',
  robots: 'noindex, nofollow',
};

export default function SitemapStaticPage() {
  const defaultSitemapData = {
    title: 'Site Map',
    description: 'A complete overview of all pages on our website.',
    mainPages: [
      { label: 'Home', url: '/' },
      { label: 'About Us', url: '/about-us/' },
      { label: 'How It Works', url: '/how-it-works/' },
      { label: 'Contact Us', url: '/contact-us/' },
      { label: 'Schedule Appointment', url: '/schedule-appointment/' },
      { label: 'Blog', url: '/blog/' },
      { label: 'Privacy Policy', url: '/privacy-policy/' },
      { label: 'Terms & Conditions', url: '/terms-conditions/' },
    ],
    caseStudies: [
      { label: 'All Case Studies', url: '/case-study/' },
      { label: 'HVAC', url: '/case-study/hvac/' },
      { label: 'Zenison Spa Therapy', url: '/case-study/zenison-spa-therapy/' },
      { label: 'Investigation Hotline', url: '/case-study/investigation-hotline/' },
      { label: 'Locks and Door', url: '/case-study/locks-and-door/' },
      { label: 'Locksmith', url: '/case-study/locksmith/' },
      { label: 'Home Decor', url: '/case-study/home-decor/' },
      { label: 'Blogging Website', url: '/case-study/blogging-website/' },
      { label: 'Automotive', url: '/case-study/automotive/' },
      { label: 'Finance', url: '/case-study/finance/' },
      { label: 'Auto Parts', url: '/case-study/auto-parts/' },
      { label: 'Universal Pest Control', url: '/case-study/universal-pest-control/' },
      { label: 'Auto Protect', url: '/case-study/auto-protect/' },
      { label: 'iRetex Premier', url: '/case-study/iretex-premier/' },
      { label: 'Water WorkzTX', url: '/case-study/water-workztx/' },
      { label: 'She Lives Beauty', url: '/case-study/she-lives-beauty/' },
      { label: 'GK Blinds', url: '/case-study/gkblinds/' },
      { label: '911 Garage Door Pros', url: '/case-study/911-garage-door-pros/' },
      { label: 'Just Voda', url: '/case-study/just-voda/' },
      { label: 'Rehvive', url: '/case-study/rehvive/' },
      { label: 'Lifecore Flooring', url: '/case-study/lifecore-flooring/' },
      { label: 'Dollar General', url: '/case-study/dollar-general/' },
    ],
    reviewProducts: [
      { label: 'Buy Reviews Online', url: '/services/buy-reviews-online/' },
      { label: 'Ambition Box Reviews', url: '/products/buy-ambition-box-reviews/reviews/' },
      { label: 'Apartment Reviews', url: '/products/buy-apartment-reviews/reviews/' },
      { label: 'AutoTrader Reviews', url: '/products/buy-autotrader-reviews/reviews/' },
      { label: 'Avvo Reviews', url: '/products/buy-avvo-reviews/reviews/' },
      { label: 'Bark Reviews', url: '/products/buy-bark-reviews/reviews/' },
      { label: 'BBB Reviews', url: '/products/buy-bbb-reviews/reviews/' },
      { label: 'Birdeye Reviews', url: '/products/buy-birdeye-reviews/reviews/' },
      { label: 'Booking Reviews', url: '/products/buy-booking-com-reviews/reviews/' },
      { label: 'BookMyShow Reviews', url: '/products/buy-bookmyshow-reviews/reviews/' },
      { label: 'BuildZoom Reviews', url: '/products/buy-buildzoom-reviews/reviews/' },
      { label: 'CarGurus Reviews', url: '/products/buy-cargurus-reviews/reviews/' },
      { label: 'ChamberofCommerce Reviews', url: '/products/buy-chamberofcommerce/reviews/' },
      { label: 'Chrome Extension Reviews', url: '/products/buy-chrome-extension-reviews/reviews/' },
      { label: 'Consumeraffairs.com Reviews', url: '/products/buy-consumeraffairs-com-reviews/reviews/' },
      { label: 'CustomerLobby Reviews', url: '/products/buy-customerlobby-reviews/reviews/' },
      { label: 'Dealerrater Reviews', url: '/products/buy-dealerrater-reviews/reviews/' },
      { label: 'Designrush Reviews', url: '/products/buy-designrush-reviews/reviews/' },
      { label: 'Energysage Reviews', url: '/products/buy-energysage-reviews/reviews/' },
      { label: 'Expedia Reviews', url: '/products/buy-expedia-reviews/reviews/' },
      { label: 'Facebook Reviews', url: '/products/buy-facebook-reviews/reviews/' },
      { label: 'Findlaw Reviews', url: '/products/buy-findlaw-reviews/reviews/' },
      { label: 'FoodDrop Reviews', url: '/products/buy-fooddrop-reviews/reviews/' },
      { label: 'Free Google Reviews', url: '/grb/product/get-free-google-reviews/' },
      { label: 'Glassdoor Reviews', url: '/products/buy-glassdoor-reviews/reviews/' },
      { label: 'Google GPS Reviews', url: '/products/buy-google-gps-reviews/reviews/' },
      { label: 'Google Local Guide Reviews', url: '/products/buy-google-local-guide-reviews/reviews/' },
      { label: 'Google LSA Reviews', url: '/products/buy-google-lsa-reviews/reviews/' },
      { label: 'Google Playstore Reviews', url: '/products/buy-google-play-store-reviews/reviews/' },
      { label: 'Google Reviews', url: '/products/buy-google-review/reviews/' },
      { label: 'Healthgrades Reviews', url: '/products/buy-healthgrades-reviews/reviews/' },
      { label: 'HelloPeter.com Reviews', url: '/products/buy-hellopeter-reviews/reviews/' },
      { label: 'Home Advisor Reviews', url: '/products/buy-home-advisor-reviews/reviews/' },
      { label: 'Home Star Reviews', url: '/products/buy-homestars-reviews/reviews/' },
      { label: 'HomeToGo Reviews', url: '/products/buy-hometogo-reviews/reviews/' },
      { label: 'Homelight Reviews', url: '/products/buy-homelight-reviews/reviews/' },
      { label: 'Hotels Reviews', url: '/products/buy-hotels-com-reviews/reviews/' },
      { label: 'Houzz Reviews', url: '/products/buy-houzz-reviews/reviews/' },
      { label: 'IMDb Reviews', url: '/products/buy-imdb-reviews/reviews/' },
      { label: 'Indeed Reviews', url: '/products/buy-indeed-reviews/reviews/' },
      { label: 'JobStreet Reviews', url: '/products/buy-jobstreet-reviews/reviews/' },
      { label: 'Magikpet Reviews', url: '/products/buy-magikpet-reviews/reviews/' },
      { label: 'Makeupalley Reviews', url: '/products/buy-makeupalley-reviews/reviews/' },
      { label: 'Mortgage Matchup Reviews', url: '/products/buy-mortgage-matchupreviews/reviews/' },
      { label: 'Networx Reviews', url: '/products/buy-networx-reviews/reviews/' },
      { label: 'Niche.com Reviews', url: '/products/buy-niche-reviews/reviews/' },
      { label: 'Product Reviews', url: '/products/buy-product-reviews/reviews/' },
      { label: 'QuickBooks Review', url: '/products/buy-quickbooks-review/reviews/' },
      { label: 'RateMds Reviews', url: '/products/buy-ratemds-reviews/reviews/' },
      { label: 'RealEstateAgents Reviews', url: '/products/buy-realestateagents-reviews/reviews/' },
      { label: 'RealSelf Reviews', url: '/products/buy-realself-reviews/reviews/' },
      { label: 'Realtor Reviews', url: '/products/buy-realtor-reviews/reviews/' },
      { label: 'Rehab.com Reviews', url: '/products/buy-rehab-reviews/reviews/' },
      { label: 'ReportTotal Reviews', url: '/products/buy-reporttotal-reviews/reviews/' },
      { label: 'Review Centre Reviews', url: '/products/buy-review-centre-reviews/reviews/' },
      { label: 'Reviews.io Reviews', url: '/products/buy-reviews-io-reviews/reviews/' },
      { label: 'REW Reviews', url: '/products/buy-rew-reviews/reviews/' },
      { label: 'SaaSHub Reviews', url: '/products/buy-saashub-reviews/reviews/' },
      { label: 'Scamvoid Reviews', url: '/products/buy-scamvoid-reviews/reviews/' },
      { label: 'Seek.com Reviews', url: '/products/buy-seek-com/reviews/' },
      { label: 'Sitejabber Reviews', url: '/products/buy-sitejabber-reviews/reviews/' },
      { label: 'Solar Choice', url: '/products/buy-solar-choice/reviews/' },
      { label: 'Solar Reviews', url: '/products/buy-solarreviews/reviews/' },
      { label: 'Sortlist Reviews', url: '/products/buy-sortlist-reviews/reviews/' },
      { label: 'Source Forge Reviews', url: '/products/buy-source-forge-reviews/reviews/' },
      { label: 'Spotify', url: '/products/buy-spotify/reviews/' },
      { label: 'Thumbtack Reviews', url: '/products/buy-thumbtack-reviews/reviews/' },
      { label: 'TopSEOs Reviews', url: '/products/buy-topseos-reviews/reviews/' },
      { label: 'Transport Reviews', url: '/products/buy-transport-reviews/reviews/' },
      { label: 'TrustPilot Reviews', url: '/products/buy-trustpilot-reviews/reviews/' },
      { label: 'Trustpilot Verified Reviews', url: '/products/buy-trustpilot-verified-reviews/reviews/' },
      { label: 'Trustedpros Reviews', url: '/products/buy-trustedpros/reviews/' },
      { label: 'UpCity Reviews', url: '/products/buy-upcity-reviews/reviews/' },
      { label: 'Vitals Reviews', url: '/products/buy-vitals-com-reviews/reviews/' },
      { label: 'Web Retailer Reviews', url: '/products/buy-web-retailer-reviews/reviews/' },
      { label: 'WebMD Reviews', url: '/products/buy-webmd-reviews/reviews/' },
      { label: 'WeddingWire Reviews', url: '/products/buy-weddingwire-reviews/reviews/' },
      { label: 'WYL.co Reviews', url: '/products/buy-wyl-page-reviews/reviews/' },
      { label: 'YellowPages Reviews', url: '/products/buy-yellowpages-reviews/reviews/' },
      { label: 'Yelp Reviews', url: '/products/buy-5-star-positive-yelp-reviews/reviews/' },
      { label: 'Zillow Reviews', url: '/products/buy-zillow-reviews/reviews/' },
    ],
  };

  return <SitemapSection id="static-sitemap" data={defaultSitemapData} settings={{} as any} />;
}
