export const countryCodes = [
  { code: "+1", iso: "us", name: "United States" },
  { code: "+1", iso: "ca", name: "Canada" },
  { code: "+7", iso: "ru", name: "Russia" },
  { code: "+20", iso: "eg", name: "Egypt" },
  { code: "+27", iso: "za", name: "South Africa" },
  { code: "+30", iso: "gr", name: "Greece" },
  { code: "+31", iso: "nl", name: "Netherlands" },
  { code: "+32", iso: "be", name: "Belgium" },
  { code: "+33", iso: "fr", name: "France" },
  { code: "+34", iso: "es", name: "Spain" },
  { code: "+36", iso: "hu", name: "Hungary" },
  { code: "+39", iso: "it", name: "Italy" },
  { code: "+40", iso: "ro", name: "Romania" },
  { code: "+41", iso: "ch", name: "Switzerland" },
  { code: "+43", iso: "at", name: "Austria" },
  { code: "+44", iso: "gb", name: "United Kingdom" },
  { code: "+45", iso: "dk", name: "Denmark" },
  { code: "+46", iso: "se", name: "Sweden" },
  { code: "+47", iso: "no", name: "Norway" },
  { code: "+48", iso: "pl", name: "Poland" },
  { code: "+49", iso: "de", name: "Germany" },
  { code: "+51", iso: "pe", name: "Peru" },
  { code: "+52", iso: "mx", name: "Mexico" },
  { code: "+53", iso: "cu", name: "Cuba" },
  { code: "+54", iso: "ar", name: "Argentina" },
  { code: "+55", iso: "br", name: "Brazil" },
  { code: "+56", iso: "cl", name: "Chile" },
  { code: "+57", iso: "co", name: "Colombia" },
  { code: "+58", iso: "ve", name: "Venezuela" },
  { code: "+60", iso: "my", name: "Malaysia" },
  { code: "+61", iso: "au", name: "Australia" },
  { code: "+62", iso: "id", name: "Indonesia" },
  { code: "+63", iso: "ph", name: "Philippines" },
  { code: "+64", iso: "nz", name: "New Zealand" },
  { code: "+65", iso: "sg", name: "Singapore" },
  { code: "+66", iso: "th", name: "Thailand" },
  { code: "+81", iso: "jp", name: "Japan" },
  { code: "+82", iso: "kr", name: "South Korea" },
  { code: "+84", iso: "vn", name: "Vietnam" },
  { code: "+86", iso: "cn", name: "China" },
  { code: "+90", iso: "tr", name: "Turkey" },
  { code: "+91", iso: "in", name: "India" },
  { code: "+92", iso: "pk", name: "Pakistan" },
  { code: "+93", iso: "af", name: "Afghanistan" },
  { code: "+94", iso: "lk", name: "Sri Lanka" },
  { code: "+95", iso: "mm", name: "Myanmar" },
  { code: "+98", iso: "ir", name: "Iran" },
  { code: "+212", iso: "ma", name: "Morocco" },
  { code: "+213", iso: "dz", name: "Algeria" },
  { code: "+216", iso: "tn", name: "Tunisia" },
  { code: "+218", iso: "ly", name: "Libya" },
  { code: "+220", iso: "gm", name: "Gambia" },
  { code: "+221", iso: "sn", name: "Senegal" },
  { code: "+224", iso: "gn", name: "Guinea" },
  { code: "+225", iso: "ci", name: "Ivory Coast" },
  { code: "+227", iso: "ne", name: "Niger" },
  { code: "+228", iso: "tg", name: "Togo" },
  { code: "+229", iso: "bj", name: "Benin" },
  { code: "+230", iso: "mu", name: "Mauritius" },
  { code: "+231", iso: "lr", name: "Liberia" },
  { code: "+232", iso: "sl", name: "Sierra Leone" },
  { code: "+233", iso: "gh", name: "Ghana" },
  { code: "+234", iso: "ng", name: "Nigeria" },
  { code: "+235", iso: "td", name: "Chad" },
  { code: "+237", iso: "cm", name: "Cameroon" },
  { code: "+238", iso: "cv", name: "Cape Verde" },
  { code: "+241", iso: "ga", name: "Gabon" },
  { code: "+242", iso: "cg", name: "Republic of the Congo" },
  { code: "+243", iso: "cd", name: "DR Congo" },
  { code: "+244", iso: "ao", name: "Angola" },
  { code: "+248", iso: "sc", name: "Seychelles" },
  { code: "+249", iso: "sd", name: "Sudan" },
  { code: "+250", iso: "rw", name: "Rwanda" },
  { code: "+251", iso: "et", name: "Ethiopia" },
  { code: "+252", iso: "so", name: "Somalia" },
  { code: "+253", iso: "dj", name: "Djibouti" },
  { code: "+254", iso: "ke", name: "Kenya" },
  { code: "+255", iso: "tz", name: "Tanzania" },
  { code: "+256", iso: "ug", name: "Uganda" },
  { code: "+257", iso: "bi", name: "Burundi" },
  { code: "+258", iso: "mz", name: "Mozambique" },
  { code: "+260", iso: "zm", name: "Zambia" },
  { code: "+261", iso: "mg", name: "Madagascar" },
  { code: "+263", iso: "zw", name: "Zimbabwe" },
  { code: "+264", iso: "na", name: "Namibia" },
  { code: "+265", iso: "mw", name: "Malawi" },
  { code: "+266", iso: "ls", name: "Lesotho" },
  { code: "+267", iso: "bw", name: "Botswana" },
  { code: "+268", iso: "sz", name: "Eswatini" },
  { code: "+291", iso: "er", name: "Eritrea" },
  { code: "+297", iso: "aw", name: "Aruba" },
  { code: "+298", iso: "fo", name: "Faroe Islands" },
  { code: "+299", iso: "gl", name: "Greenland" },
  { code: "+350", iso: "gi", name: "Gibraltar" },
  { code: "+351", iso: "pt", name: "Portugal" },
  { code: "+352", iso: "lu", name: "Luxembourg" },
  { code: "+353", iso: "ie", name: "Ireland" },
  { code: "+354", iso: "is", name: "Iceland" },
  { code: "+355", iso: "al", name: "Albania" },
  { code: "+356", iso: "mt", name: "Malta" },
  { code: "+357", iso: "cy", name: "Cyprus" },
  { code: "+358", iso: "fi", name: "Finland" },
  { code: "+359", iso: "bg", name: "Bulgaria" },
  { code: "+370", iso: "lt", name: "Lithuania" },
  { code: "+371", iso: "lv", name: "Latvia" },
  { code: "+372", iso: "ee", name: "Estonia" },
  { code: "+373", iso: "md", name: "Moldova" },
  { code: "+374", iso: "am", name: "Armenia" },
  { code: "+375", iso: "by", name: "Belarus" },
  { code: "+376", iso: "ad", name: "Andorra" },
  { code: "+377", iso: "mc", name: "Monaco" },
  { code: "+380", iso: "ua", name: "Ukraine" },
  { code: "+381", iso: "rs", name: "Serbia" },
  { code: "+382", iso: "me", name: "Montenegro" },
  { code: "+385", iso: "hr", name: "Croatia" },
  { code: "+386", iso: "si", name: "Slovenia" },
  { code: "+387", iso: "ba", name: "Bosnia and Herzegovina" },
  { code: "+389", iso: "mk", name: "North Macedonia" },
  { code: "+420", iso: "cz", name: "Czech Republic" },
  { code: "+421", iso: "sk", name: "Slovakia" },
  { code: "+501", iso: "bz", name: "Belize" },
  { code: "+502", iso: "gt", name: "Guatemala" },
  { code: "+503", iso: "sv", name: "El Salvador" },
  { code: "+504", iso: "hn", name: "Honduras" },
  { code: "+505", iso: "ni", name: "Nicaragua" },
  { code: "+506", iso: "cr", name: "Costa Rica" },
  { code: "+507", iso: "pa", name: "Panama" },
  { code: "+509", iso: "ht", name: "Haiti" },
  { code: "+591", iso: "bo", name: "Bolivia" },
  { code: "+592", iso: "gy", name: "Guyana" },
  { code: "+593", iso: "ec", name: "Ecuador" },
  { code: "+595", iso: "py", name: "Paraguay" },
  { code: "+597", iso: "sr", name: "Suriname" },
  { code: "+598", iso: "uy", name: "Uruguay" },
  { code: "+673", iso: "bn", name: "Brunei" },
  { code: "+675", iso: "pg", name: "Papua New Guinea" },
  { code: "+676", iso: "to", name: "Tonga" },
  { code: "+677", iso: "sb", name: "Solomon Islands" },
  { code: "+678", iso: "vu", name: "Vanuatu" },
  { code: "+679", iso: "fj", name: "Fiji" },
  { code: "+680", iso: "pw", name: "Palau" },
  { code: "+685", iso: "ws", name: "Samoa" },
  { code: "+686", iso: "ki", name: "Kiribati" },
  { code: "+687", iso: "nc", name: "New Caledonia" },
  { code: "+689", iso: "pf", name: "French Polynesia" },
  { code: "+852", iso: "hk", name: "Hong Kong" },
  { code: "+853", iso: "mo", name: "Macau" },
  { code: "+855", iso: "kh", name: "Cambodia" },
  { code: "+856", iso: "la", name: "Laos" },
  { code: "+880", iso: "bd", name: "Bangladesh" },
  { code: "+886", iso: "tw", name: "Taiwan" },
  { code: "+960", iso: "mv", name: "Maldives" },
  { code: "+961", iso: "lb", name: "Lebanon" },
  { code: "+962", iso: "jo", name: "Jordan" },
  { code: "+963", iso: "sy", name: "Syria" },
  { code: "+964", iso: "iq", name: "Iraq" },
  { code: "+965", iso: "kw", name: "Kuwait" },
  { code: "+966", iso: "sa", name: "Saudi Arabia" },
  { code: "+967", iso: "ye", name: "Yemen" },
  { code: "+968", iso: "om", name: "Oman" },
  { code: "+970", iso: "ps", name: "Palestine" },
  { code: "+971", iso: "ae", name: "UAE" },
  { code: "+972", iso: "il", name: "Israel" },
  { code: "+973", iso: "bh", name: "Bahrain" },
  { code: "+974", iso: "qa", name: "Qatar" },
  { code: "+975", iso: "bt", name: "Bhutan" },
  { code: "+976", iso: "mn", name: "Mongolia" },
  { code: "+977", iso: "np", name: "Nepal" },
  { code: "+992", iso: "tj", name: "Tajikistan" },
  { code: "+993", iso: "tm", name: "Turkmenistan" },
  { code: "+994", iso: "az", name: "Azerbaijan" },
  { code: "+995", iso: "ge", name: "Georgia" },
  { code: "+996", iso: "kg", name: "Kyrgyzstan" },
  { code: "+998", iso: "uz", name: "Uzbekistan" },
];
